### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by milancermak** [beautyisourbusiness/cairo-goldmine#1]
Hi,

I'm the author of two projects that I believe are helpful and are missing in this list:

* [cairo-4626](https://github.com/milancermak/cairo-4626) - a EIP 4626 implementation in Cairo
* [xoroshiro-cairo](https://github.com/milancermak/xoroshiro-cairo) - a xoroshiro128** PRNG in Cairo

Not sure what's the right way to contribute. Should I open a PR or is this issue enough?

**Comment by beautyisourbusiness** [comment]
Added!
