### ISSUE TITLE
Bura card game implementation in cairo/starknet

### ISSUE THREAD

**Issue by iraklio** [beautyisourbusiness/cairo-goldmine#9]
Hello, I (almost) finished Bura card game implementation in Cairo.  Still needs few minor fixes, but hope to clean those up over next few weeks. 

https://github.com/iraklio/bura_game

https://en.wikipedia.org/wiki/Bura_(card_game)

![image](https://user-images.githubusercontent.com/20588945/181402954-58b8d146-3730-4d6b-bada-05e08aef7c4a.png)

**Comment by abstractnull** [comment]
Added! thx!
